name: Publish

on:
  push:
    branches: [ main ]

jobs:
  test_and_distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble release module
        run: ./gradlew bundleRelease

      - name: Sign release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.WISHLIST_KEYSTORE }}
          alias: ${{ secrets.WISHLIST_KEY_ALIAS }}
          keystorePassword: ${{ secrets.WISHLIST_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.WISHLIST_KEY_PASSWORD }}

      - name: Create service_account.json
        run: echo '${{ secrets.GOOGLE_SERVICES_API }}' > service_account.json

      - name: Deploy to internal testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.arreis.wishlist
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: whatsNew/
